cloud-native-edition/pygluu/kubernetes/gui/views/main.py
"""
pygluu.kubernetes.gui.views.main
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This module contain gui views as main page of gui installer

License terms and conditions for Gluu Cloud Native Edition:
https://www.apache.org/licenses/LICENSE-2.0
"""
import os
from flask import Blueprint, render_template, \
    redirect, url_for, request, session, \
    current_app, jsonify
from flask_socketio import emit
from pygtail import Pygtail
from werkzeug.utils import secure_filename
from ..extensions import socketio
from ..extensions import gluu_settings
from pygluu.kubernetes.helpers import get_logger

logger = get_logger("gluu-gui        ")
main_blueprint = Blueprint("main", __name__, template_folder="templates")


@main_blueprint.route("/")
def index():
    return render_template("index.html")


@main_blueprint.route("/install", methods=["GET", "POST"])
def install():
    if request.method == "POST":
        if request.form["confirm_params"] == "Y":
            gluu_settings.db.set("CONFIRM_PARAMS", "Y")
            return render_template("installation.html", target="install")
        else:
            gluu_settings.db.reset_data()
            return redirect(url_for("main.index"))

    session["finish_endpoint"] = request.endpoint
    return render_template("preinstall.html",
                           title="Setup install Settings",
                           setting_exist=gluu_settings.db.is_exist())


@main_blueprint.route("/install-no-wait", methods=["GET", "POST"])
def install_no_wait():
    if request.method == "POST":
        if request.form["confirm_params"] == "Y":
            gluu_settings.db.set("CONFIRM_PARAMS", "Y")
            return render_template("installation.html", target="install-no-wait")
        else:
            gluu_settings.db.reset_data()
            return redirect(url_for("main.index"))

    session["finish_endpoint"] = request.endpoint
    return render_template("preinstall.html",
                           title="Setup install Settings",
                           setting_exist=gluu_settings.db.is_exist())


@main_blueprint.route("/install-couchbase", methods=["GET", "POST"])
def install_couchbase():
    if request.method == "POST":
        if request.form["confirm_params"] == "Y":
            gluu_settings.db.set("CONFIRM_PARAMS", "Y")
            return render_template("installation.html", target="install-couchbase")
        else:
            gluu_settings.db.reset_data()
            return redirect(url_for("main.index"))

    session["finish_endpoint"] = request.endpoint
    return render_template("preinstall.html",
                           title="Setup install Settings",
                           setting_exist=gluu_settings.db.is_exist())


@main_blueprint.route("/install-couchbase-backup", methods=["GET", "POST"])
def install_couchbase_backup():
    if request.method == "POST":
        if request.form["confirm_params"] == "Y":
            gluu_settings.db.set("CONFIRM_PARAMS", "Y")
            return render_template("installation.html", target="install-couchbase-backup")
        else:
            gluu_settings.db.reset_data()
            return redirect(url_for("main.index"))

    session["finish_endpoint"] = request.endpoint
    return render_template("preinstall.html",
                           title="Setup install Settings",
                           setting_exist=gluu_settings.db.is_exist())


@main_blueprint.route("/helm-install", methods=["GET", "POST"])
def helm_install():
    if request.method == "POST":
        if request.form["confirm_params"] == "Y":
            gluu_settings.db.set("CONFIRM_PARAMS", "Y")
            return render_template("installation.html", target="helm-install")
        else:
            gluu_settings.db.reset_data()
            return redirect(url_for("main.index"))

    session["finish_endpoint"] = request.endpoint
    return render_template("preinstall.html",
                           title="Setup install Settings",
                           setting_exist=gluu_settings.db.is_exist())


@main_blueprint.route("/helm-install-gluu", methods=["GET", "POST"])
def helm_install_gluu():
    if request.method == "POST":
        if request.form["confirm_params"] == "Y":
            gluu_settings.db.set("CONFIRM_PARAMS", "Y")
            return render_template("installation.html", target="helm-install-gluu")
        else:
            gluu_settings.db.reset_data()
            return redirect(url_for("main.index"))

    session["finish_endpoint"] = request.endpoint
    return render_template("preinstall.html",
                           title="Setup install Settings",
                           setting_exist=gluu_settings.db.is_exist())


@main_blueprint.route("/generate-settings", methods=["GET", "POST"])
def generate_settings():
    if request.method == "POST":
        if request.form["confirm_params"] == "Y":
            gluu_settings.db.set("CONFIRM_PARAMS", "Y")
            return redirect(url_for("main.index"))
        else:
            gluu_settings.db.reset_data()
            return redirect(url_for("main.index"))

    session["finish_endpoint"] = request.endpoint
    return redirect(url_for("wizard.agreement"))


@main_blueprint.route("/upgrade", methods=["GET", "POST"])
def upgrade():
    if request.method == "POST":
        if request.form["confirm_params"] == "Y":
            gluu_settings.db.set("CONFIRM_PARAMS", "Y")
            return render_template("installation.html", target="upgrade")
        else:
            gluu_settings.db.reset_data()
            return redirect(url_for("main.index"))

    session["finish_endpoint"] = request.endpoint
    return render_template("preinstall.html",
                           title="Setup upgrade Settings",
                           setting_exist=gluu_settings.db.is_exist())


@main_blueprint.route("/restore", methods=["GET", "POST"])
def restore():
    if request.method == "POST":
        if request.form["confirm_params"] == "Y":
            gluu_settings.db.set("CONFIRM_PARAMS", "Y")
            return render_template("installation.html", target="restore")
        else:
            gluu_settings.db.reset_data()
            return redirect(url_for("main.index"))

    session["finish_endpoint"] = request.endpoint
    return render_template("preinstall.html",
                           title="Setup restore Settings",
                           setting_exist=gluu_settings.db.is_exist())


@main_blueprint.route("/uninstall", methods=["POST"])
def uninstall():
    if request.method == "POST":
        uninstall_confirm = request.form.get("uninstall_confirm", None)

        if uninstall_confirm == "Y":
            session["installer_target"] = request.form.get("target", None)
            session["finish_endpoint"] = request.endpoint
            settings_exist = gluu_settings.db.is_exist()
            if settings_exist:
                redirect_url = get_wizard_step()
                return redirect(redirect_url)
            else:
                return render_template("preinstall.html",
                                       title="Setup Uninstall Settings",
                                       setting_exist=settings_exist)

        if request.form["confirm_params"] == "Y":
            gluu_settings.db.set("CONFIRM_PARAMS", "Y")
            target = session["installer_target"]
            return render_template("installation.html", target=target)


def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in current_app.config['ALLOWED_EXTENSIONS']


@main_blueprint.route('/upload-settings', methods=['POST'])
def upload_file():
    if request.method == 'POST':
        if 'file' not in request.files:
            return jsonify({"success": False, 'message': 'No file uploaded'})
        file = request.files['file']

        if file.filename == '':
            return jsonify({"success": False, 'message': 'No file uploaded'})

        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            file.save(os.path.join('./', filename))
            redirect_url = get_wizard_step()
            return jsonify({"success": True,
                            'message': 'File settings has been uploaded',
                            "redirect_url": redirect_url})
        else:
            return jsonify({"success": False, 'message': 'File type not supported'})


def get_wizard_step():
    """
    Define wizard step based on settings value
    :return:
    """
    if not gluu_settings.db.get("ACCEPT_GLUU_LICENSE"):
        return url_for("wizard.agreement")

    if not gluu_settings.db.get("GLUU_VERSION"):
        return url_for("wizard.gluu_version")

    if not gluu_settings.db.get("DEPLOYMENT_ARCH"):
        return url_for("wizard.deployment_arch")

    if not gluu_settings.db.get("GLUU_NAMESPACE"):
        return url_for("wizard.gluu_namespace")

    if not gluu_settings.db.get("ENABLE_CACHE_REFRESH"):
        return url_for("wizard.optional_services")

    if not gluu_settings.db.get("INSTALL_JACKRABBIT"):
        return url_for("wizard.install_jackrabbit")

    if not gluu_settings.db.get("USE_ISTIO"):
        return url_for("wizard.install_istio")

    if not gluu_settings.db.get("HOST_EXT_IP"):
        return url_for("wizard.environment")

    if not gluu_settings.db.get("PERSISTENCE_BACKEND"):
        return url_for("wizard.persistence_backend")

    if not gluu_settings.db.get("APP_VOLUME_TYPE"):
        return url_for("wizard.volumes")

    if not gluu_settings.db.get("INSTALL_COUCHBASE") and \
            gluu_settings.db.get("PERSISTENCE_BACKEND") == "couchbase":
        return url_for("wizard.couchbase")

    if gluu_settings.db.get("PERSISTENCE_BACKEND") == "spanner":
        return url_for("wizard.google")

    if gluu_settings.db.get("PERSISTENCE_BACKEND") == "sql":
        return url_for("wizard.sql")

    if not gluu_settings.db.get("GLUU_CACHE_TYPE"):
        return url_for("wizard.cache_type")

cloud-native-edition/pygluu/kubernetes/gui/templates/base.html
{% import "forms.html" as forms %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='/img/favicon.ico') }}">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{% block title %}{% endblock %} - Gluu Cloud Native</title>
  </head>
  <body>
    
    {% for message in get_flashed_messages() %}
      <div class="flash">{{ message }}</div>
    {% endfor %}

    <div class="container">
      <div class="py-5 text-center">
        <img class="mx-auto d-block" src="{{ url_for('static', filename='img/green-logo.svg') }}" alt="Gluu green logo">
      </div>
      {% block content %}{% endblock %}
    </div>

    <script src="{{ url_for('static', filename='js/jquery-3.5.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/cronstrue.min.js') }}" async></script>
    <script src="{{ url_for('static', filename='js/notify.min.js') }}" async></script>
    {% block custom_script %} {% endblock %}
  </body>
</html>

cloud-native-edition/pygluu/kubernetes/gui/templates/forms.html
{% macro text(field, hidden=False) %}
  {% set validation = "is-invalid" if field.errors else "" %}
  <div class="form-group {{ 'collapse' if hidden else '' }}">
    {{ field.label(class_="col-form-label") }}
    {{ field(class_="form-control col-sm-5 " + validation) }}
    <small class="form-text text-muted">{{ field.description |safe }}</small>
    <div class="feedback invalid-feedback">
      {% for error in field.errors %}
        <p>{{ error }}</p>
      {% endfor %}
    </div>
  </div>
{% endmacro %}

{% macro radio(field) %}

  {% set validation = "is-invalid" if field.errors else "" %}

  <div class="form-group">
    <label class="col-form-label">{{ field.label }}</label>
    <div class="col-sm-9 {{ validation }}">
      {% for choice in field %}
      <div class="custom-control custom-radio custom-control-inline">
        {{ choice(class_="custom-control-input") }}
        {{ choice.label(class_="custom-control-label" ) }}
      </div>
      {% endfor %}

    </div>
    {% if field.description %}
      <small class="form-text text-muted">{{ field.description }}</small>
    {% endif %}
    <div class="feedback invalid-feedback">
      {% for error in field.errors %}
        <p>{{ error }}</p>
      {% endfor %}
    </div>
  </div>
{% endmacro %}

{% macro single_radio(field) %}
<div class="form-check">
    {{ field(class_="form-check-input") }}
    {{ field.label(class_="form-check-label") }}
  </div>
{% endmacro %}

{% macro password(field) %}
  {% set validation = "is-invalid" if field.errors else "" %}
  <div class="form-group">
    {{ field.label(class_="col-form-label") }}
    <div class="input-group {{ validation }}" id="show_hide_password">
      {{ field(class_="form-control col-sm-5") }}
      <div class="input-group-append">
        <span class="input-group-text"><a href="#" style="text-decoration: none; color:unset;">Show</a></span>
      </div>
    </div>
    <small class="form-text text-muted">{{ field.description }}</small>
    <div class="feedback invalid-feedback">
      {% for error in field.errors %}
        <p>{{ error }}</p>
      {% endfor %}
    </div>
  </div>
{% endmacro %}

{% macro email(field) %}
  {% set validation = "is-invalid" if field.errors else "" %}
  <div class="form-group">
    {{ field.label(class_="col-form-label") }}
    {{ field(class_="form-control col-sm-5 " + validation) }}
    <small class="form-text text-muted">{{ field.description }}</small>
    <div class="feedback invalid-feedback">
      {% for error in field.errors %}
        <p>{{ error }}</p>
      {% endfor %}
    </div>
  </div>
{% endmacro %}

{% macro select(title, name, options) %}
<div class="form-group">
    <label class="col-form-label col-sm-3" for="{{ name.replace('_', '-') }}">{{ title }}</label>
    <div class="col-sm-5">
      <select class="custom-select">
        {% for k, v in options %}
          <option value="{{ k }}">{{ v }}</option>
        {% endfor %}
      </select>
    </div>
  </div>
{% endmacro %}

{% macro hidden(name, value) %}
  <input type="hidden" name="{{ name }}" value="{{ value }}" id="{{ name.replace('_', '-') }}">
{% endmacro %}

{% macro checkbox(field) %}
{% set validation = "is-invalid" if field.errors else "" %}
<div class="form-group">
  <div class="form-check">
      {{ field(class_="form-check-input " + validation) }}
      {{ field.label(class_="form-check-label") }}
      <div class="invalid-feedback">
        {% for error in field.errors %}
          <p>{{ error }}</p>
        {% endfor %}
      </div>
    </div>
  </div>
{% endmacro %}

{% macro fileinput(field, hidden=False) %}
{% set validation = "is-invalid" if field.errors else "" %}
<div class="form-group collapse {{ 'hide' if hidden else 'show' }}">
  <div class="custom-file col-sm-5">
    {{ field(class_="custom-file-input " + validation) }}
    {{ field.label(class_="custom-file-label") }}
    <div class="invalid-feedback">
      {% for error in field.errors %}
        <p>{{ error }}</p>
      {% endfor %}
    </div>
    <small class="form-text text-muted">{{ field.description }}</small>
  </div>
</div>
{% endmacro %}


{% macro croninput(field) %}
  {% set validation = "is-invalid" if field.errors else "" %}
  <div class="form-group">
    {{ field.label(class_="col-form-label") }}
    <div class="input-group">
      {{ field(class_="form-control col-sm-5 " + validation) }}
      <div class="input-group-append" id="button-addon4">
        <button class="btn btn-outline-secondary cron-input" data-input="*/30 * * * *" type="button">Every 30 mins</button>
        <button class="btn btn-outline-secondary cron-input" data-input="0 */1 * * *" type="button">Every Hour</button>
        <button class="btn btn-outline-secondary cron-input" data-input="0 */6 * * *" type="button">Every 6 hours</button>
        <button class="btn btn-outline-secondary cron-input" data-input="0 */12 * * *" type="button">Every 12 hours</button>
        <button class="btn btn-outline-secondary cron-input" data-input="0 0 */1 * *" type="button">Every day</button>
        <button class="btn btn-outline-secondary cron-input" data-input="0 0 * * 0" type="button">Once a week</button>
        <button class="btn btn-outline-secondary cron-input" data-input="0 0 1 */1 *" type="button">Every month</button>
      </div>
    </div>
    <small class="form-text text-muted">{{ field.description }}</small>
    <div class="feedback invalid-feedback">
      {% for error in field.errors %}
        <p>{{ error }}</p>
      {% endfor %}
    </div>
  </div>
{% endmacro %}

{% macro switchbox(field) %}
  {% set validation = "is-invalid" if field.errors else "" %}
  <div class="form-group">
    <div class="custom-control custom-switch pull-right">
      {{ field.label(class_="custom-control-label") }}
      {{ field(class_="custom-control-input " + validation) }}

    </div>
  </div>
{% endmacro %}

{% macro radio_toggle(field) %}
  {% set validation = "is-invalid" if field.errors else "" %}

  <div class="form-group row {{ validation }}">
    <label class="col-sm-5 col-form-label">{{ field.label }}</label>
    <div class="col-sm-5 ">
      <ul class="radio-switch">
      {% for choice in field %}
        <li class="radio-switch__item">
          {{ choice(class_="radio-switch__input sr-only") }}
          {{ choice.label(class_="radio-switch__label" ) }}
          {% if loop.index == 2 %}
            <div aria-hidden="true" class="radio-switch__marker"></div>
          {% endif %}
        </li>
      {% endfor %}
      </ul>
    </div>
    {% if field.description %}
      <small class="form-text text-muted">{{ field.description }}</small>
    {% endif %}
    <div class="feedback invalid-feedback">
      {% for error in field.errors %}
        <p>{{ error }}</p>
      {% endfor %}
    </div>
  </div>
{% endmacro %}

{% macro radio_image(field) %}
  <div class="arch-selector">
    {% for choice in field %}
      {{ choice }}
      <label for="{{choice.id}}" class="arch-label {{ choice.data }}" data-toggle="tooltip" data-placement="bottom" title="{{ choice.label.text }}"></label>
    {% endfor %}
  </div>
{% endmacro %}

{% macro install_card(title, description, install_url, uninstall_target=None, notes=None, button_text="Install", notes_type="info", disabled=False) %}
  <div class="card shadow mb-4 bg-white rounded">
    <div class="card-body">
      {% if notes %}
          <div class="alert alert-{{ notes_type }}" role="alert">{{ notes }}</div>
      {% endif %}
      <h5 class="card-title text-primary">{{ title }}</h5>
        <p class="card-text">{{ description }}</p>
    </div>
    <div class="card-footer">
      <div class="float-right">
        {% if disabled %}
          <button class="btn btn-secondary" disabled> {{ button_text }} </button>
        {% else %}
        <a id="actionBtn" href="{{ install_url }}" class="btn btn-primary">{{ button_text }}</a>
        {% endif %}
        {% if uninstall_target %}
          <button type="button" class="mx-2 btn btn-danger float-right" data-toggle="modal" data-target="#uninstallModal" data-uninstall="{{ uninstall_target }}">Uninstall</button>
        {% endif %}
      </div>
    </div>
  </div>
{% endmacro %}

cloud-native-edition/pygluu/kubernetes/gui/templates/index.html
{% extends 'base.html' %}
{% block content %}
  <div class="card border-0 shadow p-1 mb-5 bg-white rounded">
    <div class="card-body">
      <h3 class="text-center">Gluu Cloud Native Edition</h3>
      <ul class="nav nav-pills justify-content-center" role="tablist">
        <li class="nav-item" role="presentation">
          <a class="nav-link active" id="main-tab" data-toggle="tab" href="#main" role="tab" aria-controls="main" aria-selected="true">Install Gluu</a>
        </li>
        <li class="nav-item" role="presentation">
          <a class="nav-link" id="components-tab" data-toggle="tab" href="#components" role="tab" aria-controls="components" aria-selected="false">Install Components</a>
        </li>
        <li class="nav-item" role="presentation">
          <a class="nav-link" id="utilities-tab" data-toggle="tab" href="#utilities" role="tab" aria-controls="utilities" aria-selected="false">Utilities</a>
        </li>
      </ul>

      <div class="tab-content mt-3 pl-5 pr-5">
        <div class="tab-pane active" id="main" role="tabpanel" aria-labelledby="home-tab">
          {{ forms.install_card(
                title="Helm Install",
                description="Install Gluu Cloud Native Edition using helm. This also installs the nginx-ingress chart",
                install_url=url_for('main.helm_install'),
                uninstall_target="helm-uninstall") }}
          {{ forms.install_card(
                title="Helm Install Gluu",
                description="Install Gluu Cloud Native Edition using helm. This assumes nginx-ingress is installed",
                install_url=url_for('main.helm_install_gluu'),
                uninstall_target="helm-uninstall-gluu") }}
        </div>
        <div class="tab-pane" id="components" role="tabpanel" aria-labelledby="components-tab">
          {{ forms.install_card(
                title="Install Couchbase",
                description="Install Couchbase only. Used with installation of Gluu with Helm",
                install_url=url_for('main.install_couchbase'),
                uninstall_target="uninstall-couchbase") }}
          {{ forms.install_card(
                title="Install Couchbase backup",
                description="Install Couchbase backup only.",
                install_url=url_for('main.install_couchbase_backup')) }}
        </div>
        <div class="tab-pane" id="utilities" role="tabpanel" aria-labelledby="utilities-tab">
          {{ forms.install_card(
                title="Generate settings",
                description="Generate new settings.json to install Gluu Cloud Native Edition non-interactively",
                install_url=url_for('main.generate_settings'),
                button_text="Run") }}
          {{ forms.install_card(
                title="Upgrade",
                description="Upgrade Gluu Cloud Native Edition",
                install_url=url_for('main.upgrade'),
                button_text="Not Available",
                disabled=True) }}
        </div>
      </div>
    </div>
  </div>
  <div class="modal fade" id="uninstallModal" tabindex="-1" role="dialog" aria-labelledby="uninstallModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <form action="{{ url_for('main.uninstall') }}" method="post" novalidate>
          <div class="modal-header">
            <h5 class="modal-title" id="uninstallModalLabel">Are you absolutely sure?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>

          <div class="modal-body">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <input id="target" type="hidden" name="target">
            <p>This action <strong>cannot</strong> be undone. Gluu server will be uninstall</p>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-primary" data-dismiss="modal">No</button>
            <button type="submit" name="uninstall_confirm" class="btn btn-secondary" value="Y">Yes</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

{% block custom_script %}
  <script>
  $(document).ready(function () {
    $('#uninstallModal').on('show.bs.modal', function (event) {
      var button = $(event.relatedTarget) // Button that triggered the modal
      var uninstall = button.data('uninstall') // Extract info from data-* attributes
      var modal = $(this)
      modal.find('#target').val(uninstall)
    });
  });
  </script>
{% endblock %}

cloud-native-edition/pygluu/kubernetes/gui/templates/installation.html
{% extends 'base.html' %}
{% block content %}
  <div class="card border-0 shadow p-1 mb-5 bg-white rounded">
    <div class="card-body">
      <h3 class="text-center">Gluu Cloud Native Edition</h3>
      <div class="d-flex align-items-center">
        <div>

          <input id="operationTarget" type="hidden" data-target="{{ target }}">
          <span id="progress" class="spinner-grow spinner-grow-sm text-primary" role="status" aria-hidden="true"></span>
          <span id="install_status" class="font-weight-bold"></span>
        </div>
      </div>
      <p class="text-muted text-monospace m-3"><span id="output"></span></p>
      <ul id="install_logs" class="log-box"></ul>
    </div>
    <div id="footer" class="card-footer text-center">
      <a id="finish-button" href="{{ url_for('main.index') }}" class="btn btn-primary collapse">Finish</a>
      <a id="retry-button" onclick="window.location.reload()" class="btn btn-warning collapse">Try Again</a>
      <button id="stop-button" type="button" class="mx-2 btn btn-danger" data-toggle="modal" data-target="#stopModal">Stop</button>
    </div>
  </div>
  <div class="modal fade" id="stopModal" tabindex="-1" role="dialog" aria-labelledby="stopModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <form id="stopProcess" novalidate>
          <div class="modal-header">
            <h5 class="modal-title" id="stopModalLabel">Are you absolutely sure?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>

          <div class="modal-body">
            <p>This action <strong>cannot</strong> be undone. All processes will be stopped</p>
          </div>

          <div class="modal-footer">
            <button id="ContinueConfirmBtn" type="button" class="btn btn-primary" data-dismiss="modal">Continue Anyway</button>
            <button id="StopConfirmBtn" type="submit" name="stop_confirm" class="btn btn-secondary" value="Y">
              <span id="spinner" class="spinner-border spinner-border-sm collapse" role="status" aria-hidden="true"></span>
              <span id="waitText">STOP Installation</span>
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

{% block custom_script %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.3.0/socket.io.js" integrity="sha512-v8ng/uGxkge3d1IJuEo6dJP8JViyvms0cly9pnbfRxT6/31c3dRWxIiwGnMSWwZjHKOuY3EVmijs7k1jz/9bLA==" crossorigin="anonymous"></script>
<script>
    const operationTarget = document.getElementById('operationTarget');
    const output = document.getElementById('output');
    const installStatus = document.getElementById('install_status');
    const progress = document.getElementById('progress');
    const installBtn = document.getElementById('installTrigger');
    const installLogs = document.getElementById('install_logs');
    const footer = document.getElementById('footer');
    const finishBtn = document.getElementById('finish-button');
    const retryBtn = document.getElementById('retry-button');
    const stopBtn = document.getElementById('stop-button');

    var socket = io.connect('http://' + document.domain + ':' + location.port + '/installation');

    window.addEventListener('load', (event) => {
      socket.emit('start_installation', operationTarget.dataset.target)
    });

    socket.on('response', response => {
      if(response.status == 'COMPLETED'){
        install_status.innerHTML = 'Installation Completed';
        progress.classList.add('collapse');
        finishBtn.classList.add('show');
        stopBtn.classList.add('collapse');
        socket.emit('disconnect');
      }

      install_status.innerHTML = response.title;
      if(response.log.length > 0){
        output.innerHTML = response.log;
      }

      var line = document.createElement('li');
      installLogs.prepend(response.log, line);

      if(response.status == 'ERROR'){
        install_status.innerHTML = 'Installation Error';
        progress.classList.add('collapse');
        retryBtn.classList.add('show');
        socket.emit('disconnect');
      }
    });
    const sendHttpRequest = (method, url, data) => {
      const promise = new Promise((resolve, reject) => {
        const xhr = new XMLHttpRequest();
        xhr.open(method, url);
        var csrftoken = $('meta[name=csrf-token]').attr('content')
        xhr.responseType = 'json';

        if (data) {
          xhr.setRequestHeader('Content-Type', 'application/json');
          xhr.setRequestHeader("X-CSRFToken", csrftoken)
          /*data.forEach((value, key) => {object[key] = value});*/
        }

        xhr.onload = () => {
          if (xhr.status >= 400) {
            reject(xhr.response);
          } else {
            resolve(xhr.response);
          }
        };

        xhr.onerror = () => {
          reject('Something went wrong!');
        };

        xhr.send(JSON.stringify(data));
      });
      return promise;
    };
    const form = document.getElementById( "stopProcess" );
    var formData = new FormData(form);
    form.addEventListener('submit', function(event) {
        event.preventDefault();
        var StopConfirmBtn = document.getElementById("StopConfirmBtn"),
            ContinueConfirmBtn = document.getElementById("ContinueConfirmBtn");

        document.getElementById('spinner').classList.add('show');
        document.getElementById('waitText').innerHTML = 'Please wait...';
        StopConfirmBtn.disabled = true;
        ContinueConfirmBtn.disabled = true;
        setTimeout(() => {
            sendHttpRequest('POST', '/operations/stop', formData)
            .then(responseData => {
              if(responseData.success){
               window.location = '/';
              }
            })
            .catch(err => {
              console.log(err);
            });
        }, 3000);

    });

</script>
{% endblock %}